Replace custom bool definitions with <stdbool.h>
There is the following compile error while building
with -std=gnu23, which is now default for GCC 15:

In file included from cmd_load.c:32:
include/xyzModem.h:102:22: error: 'bool' cannot be defined via 'typedef'
  102 | typedef unsigned int bool;
      |                      ^~~~
include/xyzModem.h:102:22: note: 'bool' is a keyword with '-std=c23' onwards

This removes the manual bool definitions
and includes <stdbool.h> instead.

Signed-off-by: Til Kaiser <mail@tk154.de>